/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.spruds.raincheck;

public final class R {
    public static final class array {
        public static final int history_sync_freq_options=0x7f060000;
        public static final int history_sync_freq_values=0x7f060001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int bg_stripes=0x7f020000;
        public static final int ico_about=0x7f020001;
        public static final int ico_history=0x7f020002;
        public static final int ico_refresh=0x7f020003;
        public static final int ico_settings=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int login_background=0x7f020006;
        public static final int login_background_gradient=0x7f020007;
        public static final int login_background_img=0x7f020008;
    }
    public static final class id {
        public static final int aboutWebView=0x7f090000;
        public static final int main_menu_about=0x7f090006;
        public static final int main_menu_history=0x7f090004;
        public static final int main_menu_preferences=0x7f090005;
        public static final int main_menu_refresh=0x7f090003;
        public static final int radarImageView=0x7f090002;
        public static final int radarProgressBar=0x7f090001;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int main_menu=0x7f080000;
    }
    public static final class raw {
        public static final int about=0x7f050000;
    }
    public static final class string {
        public static final int about=0x7f070002;
        public static final int app_name=0x7f070000;
        public static final int cache_size=0x7f070004;
        public static final int cache_size_desc=0x7f070005;
        public static final int data_refresh_freq_desc=0x7f070009;
        public static final int error_about_dialog=0x7f07000e;
        public static final int error_radar_image=0x7f07000d;
        public static final int history=0x7f070003;
        public static final int history_enabled_desc=0x7f070008;
        public static final int history_enabled_title=0x7f070007;
        public static final int no_history_available=0x7f07000c;
        public static final int preferences=0x7f070006;
        public static final int refresh=0x7f070001;
        public static final int refresh_frequency=0x7f07000a;
        public static final int settings=0x7f07000b;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
